app/home/forms.py
from app import app
from . import home

from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, ValidationError
from wtforms.validators import DataRequired


class Comment_Form(FlaskForm):
    comment = StringField('Comment', validators=[DataRequired()])
    submit = SubmitField('Submit')

app/home/__init__.py
# -*- coding: utf-8 -*-
"""
Created on Thu Nov 28 20:00:29 2019

@author: Olaitan
"""
from flask import Blueprint

home = Blueprint('home', __name__)

from . import routes

app/home/routes.py
# -*- coding: utf-8 -*-
from app import app
from . import home
from flask import render_template, session, redirect, url_for, request
from flask_login import login_required
from app import db
from textblob import TextBlob as blob
from sqlalchemy.sql import func

from app.home.forms import Comment_Form
from ..models import  Reviews, Movies



def get_avg_rating(movie_id):
    avg_rating = db.session.query(func.avg(Reviews.rating).label('average')).filter(Reviews.movie_id==movie_id).scalar()
    if(avg_rating):
        avg_rating += 0.01
        avg_rating = round(avg_rating, 0)
        return avg_rating
    else:
        return 'No rating yet'

def get_review_num(movie_id):
    nor = Reviews.query.filter_by(movie_id=movie_id).count() #number of reviews
    return nor

@home.route('/movie/<movie_id>')
@login_required 
def movie(movie_id):
    form = Comment_Form()
    movie_id = movie_id
    movie = Movies.query.filter_by(id=movie_id).first_or_404()
    comments = Reviews.query.filter_by(movie_id=movie_id).order_by(Reviews.timestamp.desc())
    nor = Reviews.query.filter_by(movie_id=movie_id).count() #number of reviews
    if(not comments):
        comments = None
    return render_template('home/single_movie.html', movie=movie, title='Welcome', form=form, comments=comments, nor=nor)

@home.route('/comment/<movie_id>', methods=['GET','POST'])
@login_required 
def comment(movie_id):
     form = Comment_Form()
     if form.validate_on_submit():
        user_id = session['user_id']
        comment_obj = blob(form.comment.data)
        rating = comment_obj.sentiment.polarity
        rating = round(rating, 1)
        if rating <= -0.7:
            rating = 1
        elif rating > -0.7 and rating <= -0.2:
            rating = 2
        elif rating > -0.2 and rating <=0.1:
            rating = 3
        elif rating > 0.1 and rating <= 0.6:
            rating = 4
        else:
            rating = 5
        review = Reviews(comment=form.comment.data,
                         rating = rating,
                         user_id = user_id,
                         movie_id = movie_id
                     )
        db.session.add(review)
        db.session.commit()
        avg_rating = get_avg_rating(movie_id)
        movie = Movies.query.filter_by(id=movie_id).first_or_404()
        movie.avg_rating =  avg_rating
        db.session.commit()
        return redirect(url_for('home.movie', movie_id=movie_id))

@home.route('/')
@home.route('/index')
@login_required 
def home():
    page = request.args.get('page', 1, type=int)
    movies = Movies.query.order_by(Movies.avg_rating.desc()).paginate(page, 3, False)
    return render_template('home/index.html', movies=movies, nor=get_review_num, title='Welcome')

        

app/templates/home/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Home</title>
  <link rel="stylesheet" href="{{url_for('static', filename='materialize/css/materialize.css')}}">
  <link rel="stylesheet" href="{{url_for('static', filename='css/dosis-font.css')}}">
  <link rel="stylesheet" href="{{url_for('static', filename='iconfont/material-icons.css')}}">
  <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
  <link rel="stylesheet" href="{{url_for('static', filename='slick/slick.css')}}">
  <link rel="stylesheet" href="{{url_for('static', filename='slick/slick-theme.css')}}">
</head>
<body class="grey lighten-4">

<header class="navbar-fixed">
  <nav class="blue darken-3">
    <div class="nav-wrapper">
      <div class="container">
        <a href="#" class="brand-logo">Sentiment Based Movies Rating System</a>
      
        <a href="" data-activates="mobile-demo" class="button-collapse"><i class="material-icons white-text">menu</i></a>
        <ul class="right hide-on-med-and-down">
          <li class="waves-effect waves-light"><a href="{{url_for('home.home')}}">Home</a></li>
          <li><a href="{{url_for('auth.change_password')}}">Change Password</a></li>
          <li><a href="{{url_for('auth.logout')}}">Log Out</a></li>
        </ul>
    </div>
    <ul class="side-nav" id="mobile-demo">
      <li class="waves-effect waves-light"><a href="{{url_for('home.home')}}">Home</a></li>
      <li><a href="{{url_for('auth.change_password')}}">Change Password</a></li>
      <li><a href="{{url_for('auth.logout')}}">Log Out</a></li>

    </ul>
  </div>
</nav>
</header>
<main>
<div class="container">
<div class="row">
  {% for movie in movies.items %}
  <div class="col s12 l4 m6">
    <div class="card">
      <div class="card-image col s12 l12 m12" >
        <img src="{{url_for('static', filename='movie_cover/'+movie.movie_photo)}}">
      </div>
      <div class="card-content">
        <div class="center">
        <h5><b>{{movie.movie_name}}</b></h5></div>
        {% if avg_rating == None%}
            <p3> No rating available </p3>
        {% else %}
            <p3>Average Rating:{{ movie.avg_rating }}</p3></br>
            <p3>Based on {{ nor(movie.id ) }} review(s) </p3>
        {% endif %}
      </div>
      <div class="card-action">
        <div class="center">
        <a class="waves-effect waves-light blue darken-3 btn" href="{{url_for('home.movie', movie_id=movie.id)}}">view</a>
        </div> 
        </div>
        </div>
       </div>
  {% endfor %}

    </div>
    </div>

    <ul class="pagination center-align">
    <li {% if not movies.has_prev %}class="disabled"{% else %}class="waves-effect hoverable"{% endif %}>
      <a href="{% if movies.has_prev %}{{url_for('home.home', page = movies.page - 1)}}{% else %}#{% endif %}"><i class="material-icons">chevron_left</i></a>
    </li>
    {% for p in movies.iter_pages() %}
      {% if p %}
        {% if p==movies.page %}
          <li class="active  blue darken-3"><a href="{{ url_for('home.home', page = p)}}">{{ p }}</a></li>
        {% else %}
        <li class="waves-effect hoverable white"><a href="{{ url_for('home.home', page = p)}}">{{ p }}</a></liclass="waves-effect hoverable white">
        {% endif %}
      {% endif %}
    {% endfor %}
    <li {% if not movies.has_next %}class="disabled"{% else %}class="waves-effect hoverable"{% endif %}>
      <a href="{% if movies.has_next %}{{url_for('home.home', page = movies.page + 1)}}{% else %}#{% endif %}"><i class="material-icons">chevron_right</i></a>
    </li>
    </ul>
</main>    


<footer class="page-footer blue darken-3">
  <div class="container">
          <div class="center">
            
          </div>
         
      <div class="footer-copyright">
        <div class="container">
           <div class="center"><h6>Copyright © 2019 </h6></div>
        </div>
      </div>
   </div>
 </footer>
 <script src="{{url_for('static', filename='js/jquery-3.2.1.js')}}"></script>
 <script src="{{url_for('static', filename='materialize/js/materialize.min.js')}}"></script>
 <script src="{{url_for('static', filename='js/materializescript.js')}}"></script>
</body>
</html>

app/templates/home/single_movie.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{{ movie.movie_name }}</title>
  <link rel="stylesheet" href="{{url_for('static', filename='materialize/css/materialize.css')}}">
  <link rel="stylesheet" href="{{url_for('static', filename='css/dosis-font.css')}}">
  <link rel="stylesheet" href="{{url_for('static', filename='iconfont/material-icons.css')}}">
  <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
  <link rel="stylesheet" href="{{url_for('static', filename='slick/slick.css')}}">
  <link rel="stylesheet" href="{{url_for('static', filename='slick/slick-theme.css')}}">
</head>
<body class="grey lighten-4">

<header class="navbar-fixed">
  <nav class="blue darken-3">
    <div class="nav-wrapper">
      <div class="container">
        <a href="#" class="brand-logo">Sentiment Based Movie Rating System</a>
      
        <a href="" data-activates="mobile-demo" class="button-collapse"><i class="material-icons white-text">menu</i></a>
        <ul class="right hide-on-med-and-down">
          <li class="waves-effect waves-light"><a href="{{url_for('home.home')}}">Home</a></li>
        </ul>
    </div>
    <ul class="side-nav" id="mobile-demo">
      <li class="waves-effect waves-dark"><a href="{{url_for('home.home')}}">Home</a></li>
    </ul>
  </div>
</nav>
</header>

<div class="container">
<div class="col s12 m7">
    <div class="card">
      <div class="card-image">
        <img src="{{url_for('static', filename='movie_cover/'+movie.movie_photo)}}">
      </div>
      <div class="card-stacked small">
        <div class="card-content">
          <h5 class="blue-text">DESCRIPTION</h5>
          <p>Genre: {{ movie.movie_genre }}</p><br>
          <p1 class="grey-text">{{ movie.movie_desc }}</p1>
        </div>
        </div>
        <div class="card-action">
          {% if avg_rating == None%}
            <h5> No rating available </h5>
          {% else %}
            <h6>Average Rating:{{ movie.avg_rating }}</h6>
            <h6>Based on {{ nor }} review(s) </h6>
            <div class="divider blue darken-3"></div>
          {% endif %}
          {% if comment != None %}
          <a class="blue-text"><b></b>COMMENTS</a><br><br>
          {% for comment in comments %}
          <div class="col s12 m7">
            <div class="card horizontal">
              <div class="card-image">
                <img src="">
              </div>
              <div class="card-stacked">
                <div class="card-content">
                  <p>Posted by: {{ comment.posted_by}}</p>
                  <div class="divider blue darken-3"></div>
                  <p>{{ comment.comment }}</p><br>
                  <p>{{ comment.rating }}</p><br>
                  <p2>{{ comment.timestamp }}</p2><br>
                </div>
                <div class="card-action">
                  <x-star-rating>
                    <div class="star full"></div>
                    <div class="star full"></div>
                    <div class="star"></div>
                    <div class="star"></div>
                    <div class="star"></div>
                  </x-star-rating>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
        {% endif %}
          <br><br>

          <div class='form'>
          <form action="{{url_for('home.comment', movie_id=movie.id)}}" method="post" novalidate>
              {{ form.hidden_tag() }}
            <label for="textarea1">Drop a comment!</label>
            <div class="input-field col s12">
              {{ form.comment.label }}<br>
              {{ form.comment(size=32) }}
      </div>
      <div>
        <input type="submit" value=" Submit" name="Submit" class="btn blue darken-3">
                {{ form.csrf_token }}
    </div>
      <br><br>
          </form>  
        </div>
                      </div>
                   </div>
                </div>
             </div>
           </div>
         </div>
      </div>
    </div>
  </div>
    

  <footer class="page-footer blue darken-3">
    <div class="container">
            <div class="center">
              
            </div>
           
        <div class="footer-copyright">
          <div class="container">
             <div class="center"><h6>Copyright © 2019 </h6></div>
          </div>
        </div>
     </div>
</footer>



<script src="{{url_for('static', filename='js/jquery-3.2.1.js')}}"></script>
<script src="{{url_for('static', filename='materialize/js/materialize.min.js')}}"></script>
<script src="{{url_for('static', filename='js/materializescript.js')}}"></script>
</body>
</html>